### ISSUE TITLE
Anonymous functions?

### ISSUE THREAD

**Issue by naumruso** [filmor/ierl#14]
Hey,

I checkout out your code. It's terrific, it works well in the browser. However I couldn't find a way to create anonymous functions, every time I try to create an anonymous function I get a weird error in the ierl logs, is there a way to create them without using modules?

Thanks,
Naum. 

p.s. I don't think the problem is with the anonymous functions, but rather splitting the different commands in the cell. If I run them line by line in different cells I get correct results. Can you try and run this example code in a notebook of your own and tell me if I'm just stupid or if there's a problem somewhere. Thanks again. 

```
Items12 = [{1,1}, {2,2}, {3,-3}, {4,4}, {5,-5}, {6,6}, {7,-7}, {8,8}, {9,-9}, {10,10}],
Pred = fun({Item1, Item2}) -> Item1 =:= Item2 end,
Cond = [Pred(Item12) || Item12 <- Items12],
lists:any(Pred, Items12).
```

**Comment by filmor** [comment]
Hmm, the code executes fine for me, what is the log output you are seeing and what version are you running?

**Comment by naumruso** [comment]
Sorry for the troubles. It was my mistake, the code works well. I forgot to cleanup the variable for the function. Btw, have you tried to run ierl on remote nodes? Does it work because I'm getting some reconnecting errors?

**Comment by filmor** [comment]
Sure I've tried that, it works ;)

You currently need to install the kernel accordingly, check out `ierl install --help`:

    ierl install erlang -n erl_remote --node some_remote@node --cookie some_remote_nodes_cookie

**Comment by filmor** [comment]
Open a new issue for the concrete error and I'll have a look, maybe you forgot to set the cookie :)
