### ISSUE TITLE
Connect to remote node crashes. 

### ISSUE THREAD

**Issue by naumruso** [filmor/ierl#15]
I install the ierl remote kernel with the following command on localhost (hostname is Moscow):
`ierl install erlang -n erl_node1 --node node1@Moscow --cookie 123COOKIE --user`

the Erlang node is started with:
`erl -sname node1`

Then I start the jupyter remote kernel with:
`jupyter console --kernel erl_node1`

However, at start I get the following error message:
`22:54:34.343 [error] gen_server <12623.151.0> terminated with reason: call to undefined function jup_kernel_executor:status(<0.163.0>, busy, {jup_msg,[<<"cad4e4c9-6de8068a35e6e30f23cc939f">>],#{<<"date">> => <<"2019-10-03T20:54:33.817917Z">>,...},...})
22:54:34.345 [error] CRASH REPORT Process <12623.151.0> with 1 neighbours crashed with reason: call to undefined function jup_kernel_executor:status(<0.163.0>, busy, {jup_msg,[<<"cad4e4c9-6de8068a35e6e30f23cc939f">>],#{<<"date">> => <<"2019-10-03T20:54:33.817917Z">>,...},...})
22:54:34.346 [error] Supervisor {via,jup_registry,{ierlang,kernel_sup}} had child executor started with jup_kernel_executor:start_link(ierlang, node1@Moscow, ierl_backend_erlang, #{}) at <0.163.0> exit with reason call to undefined function jup_kernel_executor:status(<0.163.0>, busy, {jup_msg,[<<"cad4e4c9-6de8068a35e6e30f23cc939f">>],#{<<"date">> => <<"2019-10-03T20:54:33.817917Z">>,...},...}) in context child_terminated`

The OS is Ubuntu 18.04 LTS. The erlang version is 21.2. For ierl I have tried with the executable that can be downloaded from github and also to compile my own. Same results. If I go back to the shell of the erlang node I do see that some code has been uploaded, i.e., the modules ierl_versions and ierl_backend_erlang appear, so I don't think it's a cookie problem. Additionally, I can start standalone erlang kernels through jupyter, it's just when I try to connect to one that I get this message.

Sorry to bother you, but it'd be really nice you we could get this fixed. I can run more tests for you, if that's what you need. 

Thanks,
Naum.

**Comment by filmor** [comment]
Thanks a lot for the info, I must have missed a few "dependencies" last time, this is fixed with https://github.com/filmor/erlang-jupyter/commit/cb74b3fc323c998a6cb95c3f517318499bd1ea46 and I'll try to build a new release this weekend.

**Comment by filmor** [comment]
I published a new release that should fix this.
