### ISSUE TITLE
Failed on 'mix escript.build' during build Dockerfile

### ISSUE THREAD

**Issue by bon2016** [filmor/ierl#21]
When I builded Dockerfile, I got the following error.

`** (Mix) Could not compile dependency :lfe, "/home/jovyan/.mix/rebar3 bare compile --paths /home/jovyan/ierl/_build/prod/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile lfe", update it with "mix deps.update lfe" or clean it with "mix deps.clean lfe"`

## Environment

Windows 11 pro
Docker Desktop 4.5.1
Docker version 20.10.12

**Comment by filmor** [comment]
The underlying issue is https://github.com/lfe/lfe/issues/384 and my current workaround stopped working (not the one from the ticket, the variant that I use in the Dockerfile). I'll try to find a permanent solution :)
