### ISSUE TITLE
Erlang runtime hangs when running module just built.

### ISSUE THREAD

**Issue by efine** [filmor/ierl#6]
## Issue

I keep getting a hang when I run an Erlang module. It works perfectly when compiled and run on the command line. Jupyter shows the Erlang kernel as "busy" and it never seems to come back.

### How to reproduce issue in Jupyter worksheet.

* Cell 1

```
In:

-module(fb).
-export([main/1]).

fizzbuzz(N, N) -> ok;
fizzbuzz(N, Hi) ->
    case {N rem 3, N rem 5} of
        {0, 0} -> print("FizzBuzz");
        {0, _} -> print("Fizz");
        {_, 0} -> print("Buzz");
        {_, _} -> print(i2l(N))
    end,
    fizzbuzz(N + 1, Hi).

i2l(N) -> integer_to_list(N).
print(S) -> io:format("~s~n", [S]).
main(_) ->
    fizzbuzz(1, 101).

Out:
{module,fb}
```

* Cell 2
```
In:

fb:main(0).

Out:
1
2
Fizz
4
Buzz
<hang>
```

## Environment

* ierl v0.3.1
* jupyter 4.4.0
* macOS High Sierra 10.13.6
* Erlang 20 (also tried 21)
* Python 3.6.5

## pip freeze

```
altgraph==0.15
ansible==2.2.0.0
awscli==1.11.175
bakeit==0.2.2
boto==2.43.0
botocore==1.7.33
certifi==2017.4.17
cffi==1.9.1
chardet==3.0.4
colorama==0.3.7
construct==2.8.7
cryptography==1.6
docutils==0.14
enum34==1.1.6
futures==3.1.1
graphiteudp==0.0.2
idna==2.5
ipaddress==1.0.17
jmespath==0.9.3
M2Crypto==0.25.1
macholib==1.9
markdown2==2.1.0
Markups==0.2.4
modulegraph==0.16
paramiko==2.0.2
progressbar==2.3
py2app==0.10
pyasn1==0.3.7
pycairo==1.17.1
pycparser==2.17
pycrypto==2.6.1
pyenchant==1.6.5
pyOpenSSL==17.1.0
pyperclip==1.5.27
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.1
rsa==3.4.2
s3transfer==0.1.11
six==1.11.0
socketcache==0.1.0
typing==3.5.2.2
urllib3==1.21.1
virtualenv==15.1.0
```

**Comment by filmor** [comment]
Thank you for the detailed bug report. I'll have a look into this issue.

**Comment by filmor** [comment]
Okay, I can reproduce the issue, oddly enough it's broken on Binder as well, but in a different way (it skips everything that would format as Fizz, Buzz or Fizzbuzz but prints all numbers). On my system it hangs in exactly the way you report, I hope I can fix this tomorrow.

**Comment by efine** [comment]
Thanks for looking into this, and thanks for making this kernel for jupyter!

**Comment by filmor** [comment]
This should be fixed with the just-released version v0.3.2. If it still doesn't work, ping me, it fixed the issues on my systems.

**Comment by efine** [comment]
It works correctly now, thanks! Will you be integrating this with Jupyter Lab someday?

**Comment by filmor** [comment]
That fact that it doesn't work on jupyterlab right now is likely another bug, I'll open one :)
