### ISSUE TITLE
Ensure that the kernel works with Jupyterlab

### ISSUE THREAD

**Issue by filmor** [filmor/ierl#7]
At least on Binder, currently the kernel does not work, not answering on any message.

**Comment by filmor** [comment]
This is fixed with the newest erlang-jupyter: https://github.com/filmor/erlang-jupyter/commit/aa831976dbfb861d7fc8760d765786fa1b8d2073

**Comment by filmor** [comment]
@efine This is in release 0.3.3, if you want to try it :)

**Comment by efine** [comment]
@filmor Thanks, I definitely will! Appreciate your effort.
